# Generated by Django 4.1.3 on 2022-11-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rat',
            name='traits',
            field=models.ManyToManyField(to='main_app.trait'),
        ),
    ]
