# Generated by Django 4.1.3 on 2022-11-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(max_length=40)),
                ('rat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rat')),
            ],
        ),
    ]
